name: 1 - hello - world

on: push

jobs:
    first-job:
        runs-on: ubuntu-latest
        steps:
            - name: Print hello
              run: echo "Hello World"

    second-job:
        runs-on: ubuntu-latest
        steps:
            - name: Print Hi to you
              run: echo "Hi to you"

            - name: I will fail
              run: exit 1

            - name: Say goodby
              run: echo "Goodby"
